static/app.js

small change for codeclimate
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/88%23issuecomment-74337413%22%2C%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/88%23issuecomment-74339556%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/88%23issuecomment-74337413%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Snkz%20do%20I%20have%20your%20word%20that%20this%20is%20cool%20to%20merge%20into%20master%3F%22%2C%20%22created_at%22%3A%20%222015-02-13T22%3A20%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2337403%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//githu …

js moves ALL variable declaration to top of function

---

.travis.yml

This doesn't actually do anything yet... I think?
See https://github.com/travis-ci/travis-ci/issues/3239
<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/93?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/93'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Travis cache pip

---

pages/util/base.py
settings.py
webapp.py

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/94?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/94'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Convenient user testing

---

api/aggregation.py
api/submission.py
api/survey.py
api/user.py
benchmark/benchmark.py
db/__init__.py
db/answer.py
db/answer_choice.py
db/auth_user.py
db/question.py
db/question_branch.py
db/question_choice.py
db/submission.py
db/survey.py
pages/api/aggregations.py
pages/api/submissions.py
pages/api/surveys.py
pages/debug.py
pages/util/base.py
pages/view/submissions.py
pages/view/surveys.py
pages/view/visualize.py
tests/api_test.py
tests/db_test.py
tests/selenium_test.py
tests/webapp_test.py
webapp.py

...
Sorry @Snkz
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/vr2262%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2337403%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/97%23issuecomment-75594871%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-02-23T17%3A55%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2337403%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vr2262%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/SEL-Co …

One connection per handler

---

.travis.yml
dokomoforms/settings.py
tests/selenium_test.py

It actually works
<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/108?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/108'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

One more shot at xvfb selenium tests

---

tests/selenium_test.py

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/112?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/112'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Add test for multiselect question

---

provision.sh
requirements.txt
tests/api_test.py

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/114?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/114'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Update SQLAlchemy 0.9.8 -> 0.9.9

---

.travis.yml
js_tests/emulate_dom.js
package.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/SEL-Columbia/dokomoforms/commit/8559453d28e81fff398b498b7ac1f1558b323287%23commitcomment-10375238%22%2C%20%22https%3A//github.com/SEL-Columbia/dokomoforms/commit/8559453d28e81fff398b498b7ac1f1558b323287%23commitcomment-10375293%22%5D%2C%20%22comments%22%3A%20%7B%22Commit%208559453d28e81fff398b498b7ac1f1558b323287%20js_tests/emulate_dom.js%205%2012%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/SEL-Columbia/dokomoforms/commit/8559453d28e81fff398b498b7ac1f1558b323287%23commitcomment-10375238%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Snkz%20Myf%20says%20you%20messed%20up.%22%2C%20%22created_at%22%3A%20%222015-03-24T19%3A22%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20 …

Iojs take two

---

.travis.yml
js_tests/emulate_dom.js
package.json

Reverts SEL-Columbia/dokomoforms#118
<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/119?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/119'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Revert "Iojs take two"

---

dokomoforms/static/app.js
tests/selenium_test.py

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/123%23issuecomment-88189036%22%2C%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/123%23issuecomment-88189342%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/123%23issuecomment-88189036%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Here%27s%20the%20build%20matrix%3A%5Cr%5Cnhttps%3A//travis-ci.org/dokomo-sauce-matrix/dokomoforms/builds/56594328%5Cr%5Cn%5Cr%5CnLooks%20like%20%40jmwohl%27s%20suggestion%20worked.%22%2C%20%22created_at%22%3A%20%222015-03-31T17%3A59%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/233 …

jquery-ify classList stuff

---

dokomoforms/api/survey.py
dokomoforms/static/app.js
dokomoforms/templates/survey.html
js_tests/widgets.html
tests/fixtures/all-encompassing.sql

@vr2262 one line change to the python
<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/124?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/124'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Survey meta

---

dokomoforms/db/survey.py
dokomoforms/handlers/api/aggregations.py
dokomoforms/handlers/api/data_table.py
dokomoforms/handlers/api/submissions.py
dokomoforms/handlers/api/surveys.py
dokomoforms/handlers/util/base.py
dokomoforms/handlers/view/submissions.py
dokomoforms/handlers/view/surveys.py
dokomoforms/templates/base.html
dokomoforms/templates/view-submissions.html
dokomoforms/templates/view.html
tests/db_test.py
tests/handlers_test.py
tests/selenium_test.py
webapp.py

This pretty much just adds the DataTables in /view and /view/{survey_id}
<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/126?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/126'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Merge staging into rachet [sic]

---

requirements.txt

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/129?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/129'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Tornado 4.0.2 -> 4.1

---

dokomoforms/api/submission.py
tests/api_test.py

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/132?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/132'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Oops, didn't ORDER BY

---

README.md

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/142?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/142'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

adding docker docs

---

.travis.yml
dokomoforms/api/base.py
dokomoforms/api/submissions.py
dokomoforms/api/surveys.py
dokomoforms/handlers/__init__.py
dokomoforms/handlers/auth.py
dokomoforms/handlers/debug.py
dokomoforms/models/__init__.py
dokomoforms/models/util.py
dokomoforms/options.py
tests/test_api.py
tests/test_db.py
tests/test_handlers.py
tests/test_model.py
tests/test_selenium.py
tests/test_webapp.py
tests/util.py
tox.ini
webapp.py

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/153?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/153'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Phoenix reacts selenium tests

---

dokomoforms/models/answer.py
dokomoforms/static/src/survey/js/components/Photo.js
dokomoforms/templates/view_submission.html
tests/python/test_selenium.py

Fixes issue in FF for camera selection.

fallbacks for camera source

---

dokomoforms/static/src/survey/js/components/Photo.js
dokomoforms/static/src/survey/js/components/baseComponents/PhotoPreview.js
dokomoforms/static/src/survey/less/survey.less

Added react lifecycle method 'componentWillUnmount' to Photo component in which camera stream is stopped.

stop camera stream when leaving photo question [Finishes #106217586]

---

dokomoforms/static/src/admin/js/account-overview.js
tests/python/test_selenium.py

Very minor change, but don't want to forget about it... just makes the survey title a link in the datatable.

Title is now a link in Surveys datatable [Finishes #93653640]

---

dokomoforms/static/src/survey/js/Application.js
dokomoforms/static/src/survey/js/api/FacilityAPI.js
dokomoforms/static/src/survey/js/components/Header.js
dokomoforms/static/src/survey/js/components/baseComponents/Menu.js
tests/python/test_selenium.py

- facilities are only fetched from Revisit automatically on initial load
- when online, user can select 'Reload Facilities' from the dropdown to pull the facilities from Revisit.

Modified revisit interaction.

---

config.py
dokomoforms/options.py
local_config.py.example
webapp.py

Added local_config.py.example

---

tests/python/test_selenium.py

Selenium android 4.4 fixup

---

dokomoforms/options.py
local_config.py.example

use ssl for revisit

---

docker-compose.yml
dokomoforms/static/src/survey/js/components/Photo.js
installer.sh
tests/python/test_selenium.py

0.2.6 Release

---

README.md
docker-compose.yml
dokomoforms/handlers/util.py
dokomoforms/static/manifest.json
dokomoforms/static/src/admin/js/account-overview.js
dokomoforms/static/src/common/js/service-worker.js
dokomoforms/templates/base.html
dokomoforms/templates/view_enumerate.html
dokomoforms/templates/view_visualize.html
installer.sh
tests/python/branch-heaven-fixture.py
tests/python/test_selenium.py
tox.ini
webapp.py

- Fixed map http problem
- Fixed flake8 compliance
- Set both `child-src` and `frame-src` in content security policy
- Added a web app manifest and dummy service worker (which may not be working quite right...)

0.2.8 Release
